# Generated by Django 2.2.4 on 2020-05-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0002_billinginfo_paymentinfo_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products'),
            preserve_default=False,
        ),
    ]
