# Generated by Django 2.2.4 on 2020-05-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0005_auto_20200528_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='expiration_year',
            new_name='security_number',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='expiration_month',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='expiration_date',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
