# Generated by Django 2.2.4 on 2020-05-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0005_auto_20200528_1726'),
        ('productsApp', '0005_auto_20200528_2323'),
    ]

    operations = [
    ]
