# Generated by Django 2.2.4 on 2020-05-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productsApp.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoppingCart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productsApp.ShoppingCart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wishList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productsApp.WishList'),
        ),
    ]
